---
- name: Install Docker on all instances
  hosts: all
  become: yes
  roles:
    - docker

- name: Deploy backend (Redis + Worker containers)
  hosts: jke-redis-worker
  become: yes
  roles:
    - backend

- name: Deploy frontend (Vote + Result containers)
  hosts: jke-bastion
  become: yes
  roles:
    - frontend

- name: Deploy database (PostgreSQL container)
  hosts: jke-postgres
  become: yes
  roles:
    - database
